client: my_windows_client
user: administration

#Precondition:
# Create a user with admin rights on the Windows Station, i.e. "administration" or use the internal administration user "Administrator" 
# install cygwin
# in cygwin with admin rights do: mkpasswd -l > /etc/passwd
# and: mkgroup -l > /etc/group (restart sshd on cygwin)
# install custom rsync-client (see below)

# If windows sleeps, it can wake up by wol to the mac (only if NIC eth is in bios enabled for this) 
wol-mac:C4:D8:D5:50:91:30
wol-net:172.16.0.255

tree: /\|tmp-drive=x\|rsync=c:/cygwin64/bin/rsync.exe\|cygpath=true\|verbose=true\|c:/Users/windowsuser

rsync-options:
# to use other rsync on winsows (here:tb-rsync-vss-64.exe) set path here
        --rsync-path="\"c:/Program Files/True_Blade_Systems/tb-rsync-vss-64.exe\""
        --no-links
# The -a (archive) flag, automatically enables -l (which tells it to copy symlinks as symlinks) in rsync. 
# --no-links explicitly overrides and disables the -l behavior. Instead of copying or following symlinks and junctions, 
#    rsync will completely ignore and skip them on the Windows host.
        --no-implied-dirs
# By default, when rsync is given a deep path, it implicitly creates missing parent directories on the destination.
# Under Windows environments, this can sometimes lead to unexpected path interpretation when dealing with hidden system junctions.
# This flag prevents rsync from making those path assumptions, providing an extra layer of protection against directory-looping bugs.

# For test tree and rsync-option parameters run on target system (check and adapt path and username):
#$ "c:/Program Files/True Blade Systems/tb-rsync-vss-64.exe" "/|tmp-drive=x|rsync=c:/cygwin64/bin/rsync.exe|cygpath=true|logfile=c:/Users/<windows_user>/tb-rsync-vss_`c:/cygwin64/bin/date +\%Y-\%m-\%d_\%H-\%M-\%S`.log|c:/Users/<windows_user>"

exclude:
# Windows excludes 
        **AppData**
        Downloads
        MicrosoftEdgeBackups/*
        OneDrive
        ntuser.*
        NTUSER.*
# links are excluded already
#        My Documents
#        My Music
#        My Pictures
#        My Videos
#My Music -> /cygdrive/c/Users/<windows_user>/Music
#My Pictures -> /cygdrive/c/Users/<windows_user>/Pictures
#My Videos -> /cygdrive/c/Users/<windows_user>/Videos
#Eigene Bilder -> /cygdrive/c/Users/<windows_user>/Pictures
#Eigene Musik -> /cygdrive/c/Users/<windows_user>/Music
#Eigene Videos -> /cygdrive/c/Users/<windows_user>/Videos
